"""
RSLI Data Lineage — Central Path Configuration
================================================
Edit the paths in this file to match your environment before running the pipeline.
All scripts read their paths from here via run_pipeline.py.

Directory layout expected after setup:
  <project_root>/
  ├── config.py               ← this file
  ├── run_pipeline.py         ← pipeline runner
  ├── *.py                    ← pipeline scripts
  ├── input/                  ← source xlsx/csv files (copy from client share)
  │   ├── DIFW_Query_Results.xlsx
  │   ├── Tidal_Deps_Last30days_as_of_20270617.csv
  │   ├── TIDAL_15_April_updated.xlsx
  │   ├── TidalJob_avg_runtime_duration.csv
  │   └── PKG_PROC_Analysis_All_Metadata.xlsx   (pre-built; overwritten by Stage 5)
  ├── All_Metadata/           ← Oracle PL/SQL .sql source files
  ├── shell_scripts/          ← TIDAL .sh scripts (from RSL-Delphi-TidalEDW_SH_scripts/)
  ├── python_data_lineage/    ← Gudu SQLFlow Lite tool (jar/ subfolder)
  └── output/                 ← all generated files land here
"""

from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# PROJECT ROOT  (auto-detected — do not change)
# ─────────────────────────────────────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parent

# ─────────────────────────────────────────────────────────────────────────────
# KEY DIRECTORIES  — change these if your folder names differ
# ─────────────────────────────────────────────────────────────────────────────
INPUT_DIR         = PROJECT_ROOT / "input"           # Source xlsx/csv files
OUTPUT_DIR        = PROJECT_ROOT / "output"          # All generated outputs
ALL_METADATA_DIR  = PROJECT_ROOT / "All_Metadata"    # Oracle PL/SQL source files
SHELL_SCRIPTS_DIR = PROJECT_ROOT / "shell_scripts"   # TIDAL .sh scripts

# ─────────────────────────────────────────────────────────────────────────────
# GUDU SQLFlow Lite  — update path if JAR is in a different location
# ─────────────────────────────────────────────────────────────────────────────
# The JAR is used by clean_and_run_gudu.py (Stage 2).
# Copy the python_data_lineage/ folder from the old project to get the JAR.
GUDU_JAR_DIR = PROJECT_ROOT / "python_data_lineage" / "jar"

# ─────────────────────────────────────────────────────────────────────────────
# INPUT FILES
# ─────────────────────────────────────────────────────────────────────────────
DIFW_QUERY_RESULTS  = INPUT_DIR / "DIFW_Query_Results.xlsx"
TIDAL_PRIMARY       = INPUT_DIR / "Tidal_Deps_Last30days_as_of_20270617.csv"
TIDAL_SUPPLEMENT    = INPUT_DIR / "TIDAL_15_April_updated.xlsx"
TIDAL_RUNTIME       = INPUT_DIR / "TidalJob_avg_runtime_duration.csv"

# PKG_PROC_Analysis is pre-supplied in input/ and regenerated by Stage 5.
# generate_pkg_proc_analysis.py writes directly to output/.
PKG_PROC_ANALYSIS   = OUTPUT_DIR / "PKG_PROC_Analysis_All_Metadata.xlsx"

# ─────────────────────────────────────────────────────────────────────────────
# GENERATED INTERMEDIATE FILES  (written by one stage, read by the next)
# ─────────────────────────────────────────────────────────────────────────────
SHELL_PARSED_CSV  = OUTPUT_DIR / "shell_parsed_objects.csv"
GUDU_LINEAGE_CSV  = OUTPUT_DIR / "gudu_lineage_output.csv"
LLM_LINEAGE_CSV   = OUTPUT_DIR / "llm_lineage_output.csv"
COMBINED_CSV      = OUTPUT_DIR / "combined_lineage_latest.csv"

# ─────────────────────────────────────────────────────────────────────────────
# LLM API  — set your Azure OpenAI / OpenAI credentials here
# (or keep them in the .env file — llm_lineage_extractor.py reads .env automatically)
# ─────────────────────────────────────────────────────────────────────────────
# AZURE_OPENAI_ENDPOINT = "https://your-resource.openai.azure.com/"
# AZURE_OPENAI_API_KEY  = "your-key-here"
# AZURE_OPENAI_DEPLOYMENT = "gpt-4o"
