"""
RSLI Data Lineage — Central Path Configuration
================================================
Edit the paths in this file to match your environment before running the pipeline.
All scripts read their paths from here via run_pipeline.py.

Directory layout expected after setup:
  <project_root>/
  ├── config.py               ← this file
  ├── run_pipeline.py         ← pipeline runner
  ├── *.py                    ← pipeline scripts
  ├── input/                  ← source xlsx/csv files (copy from client share)
  │   ├── DIFW_Query_Results.xlsx           (output of DIFW_tidal_lineage_query.sql)
  │   ├── TIDAL_15_April_updated.xlsx       (primary TIDAL dump)
  │   ├── Tidal Deps 20270713.xlsx          (supplemental TIDAL export)
  │   ├── Tidal_Deps_Last30days_as_of_20270617.csv  (supplemental 2 — 30-day CSV export)
  │   ├── TidalJob_avg_runtime_duration.csv
  │   └── PKG_PROC_Analysis_All_Metadata.xlsx   (pre-built; overwritten by Stage 5)
  ├── All_Metadata/                  ← Oracle PL/SQL .sql source files (claims domain)
  ├── Lineage_Expansion_Metadata/    ← Oracle PL/SQL .sql source files (non-claims domain, added Sept 2026)
  ├── shell_scripts/                 ← TIDAL .sh scripts
  ├── python_data_lineage/           ← Gudu SQLFlow Lite tool (jar/ subfolder)
  └── output/                        ← all generated files land here
"""

from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# PROJECT ROOT  (auto-detected — do not change)
# ─────────────────────────────────────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parent

# ─────────────────────────────────────────────────────────────────────────────
# KEY DIRECTORIES  — change these if your folder names differ
# ─────────────────────────────────────────────────────────────────────────────
INPUT_DIR         = PROJECT_ROOT / "input"           # Source xlsx/csv files
OUTPUT_DIR        = PROJECT_ROOT / "output"          # All generated outputs
ALL_METADATA_DIR  = PROJECT_ROOT / "All_Metadata"    # Oracle PL/SQL source files (claims domain, 14 RPT tables)
LINEAGE_EXPANSION_METADATA_DIR = PROJECT_ROOT / "Lineage_Expansion_Metadata"  # non-claims domain, 19 RPT tables
SHELL_SCRIPTS_DIR = PROJECT_ROOT / "shell_scripts"   # TIDAL .sh scripts

# Gudu-cleaned output dirs (one per metadata source — kept separate so a
# metadata refresh only needs to re-clean/re-run-Gudu on the changed domain).
ALL_METADATA_CLEANED_DIR      = OUTPUT_DIR / "All_Metadata_cleaned_new"
LINEAGE_EXPANSION_CLEANED_DIR = OUTPUT_DIR / "Lineage_Expansion_Metadata_cleaned"

# ─────────────────────────────────────────────────────────────────────────────
# GUDU SQLFlow Lite  — update path if JAR is in a different location
# ─────────────────────────────────────────────────────────────────────────────
# The JAR is used by clean_and_run_gudu.py (Stage 2).
# Copy the python_data_lineage/ folder from the old project to get the JAR.
GUDU_JAR_DIR = PROJECT_ROOT / "python_data_lineage"

# ─────────────────────────────────────────────────────────────────────────────
# INPUT FILES
# ─────────────────────────────────────────────────────────────────────────────
DIFW_QUERY_RESULTS  = INPUT_DIR / "DIFW_Query_Results.xlsx"
TIDAL_PRIMARY       = INPUT_DIR / "TIDAL_15_April_updated.xlsx"
TIDAL_SUPPLEMENT    = INPUT_DIR / "Tidal Deps 20270713.xlsx"
TIDAL_SUPPLEMENT2   = INPUT_DIR / "Tidal_Deps_Last30days_as_of_20270617.csv"
TIDAL_RUNTIME       = INPUT_DIR / "TidalJob_avg_runtime_duration.csv"

# PKG_PROC_Analysis is pre-supplied in input/ and regenerated by Stage 5.
# generate_pkg_proc_analysis.py writes directly to output/.
PKG_PROC_ANALYSIS   = OUTPUT_DIR / "PKG_PROC_Analysis_All_Metadata.xlsx"

# ─────────────────────────────────────────────────────────────────────────────
# GENERATED INTERMEDIATE FILES  (written by one stage, read by the next)
# ─────────────────────────────────────────────────────────────────────────────
SHELL_PARSED_CSV  = OUTPUT_DIR / "shell_parsed_objects.csv"
GUDU_LINEAGE_CSV  = OUTPUT_DIR / "gudu_lineage_output.csv"
LLM_LINEAGE_CSV   = OUTPUT_DIR / "llm_lineage_output.csv"
COMBINED_CSV      = OUTPUT_DIR / "combined_lineage_latest_expanded.csv"

# ─────────────────────────────────────────────────────────────────────────────
# LLM API  — set your Azure OpenAI / OpenAI credentials here
# (or keep them in the .env file — llm_lineage_extractor.py reads .env automatically)
# ─────────────────────────────────────────────────────────────────────────────
# AZURE_OPENAI_ENDPOINT = "https://your-resource.openai.azure.com/"
# AZURE_OPENAI_API_KEY  = "your-key-here"
# AZURE_OPENAI_DEPLOYMENT = "gpt-4o"

