--------------------------------------------------------
--  DDL for Procedure PRC_GRP_LOAD_STG_REINSURER_PREM_PCT_R_NON_LTD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ATOMIC"."PRC_GRP_LOAD_STG_REINSURER_PREM_PCT_R_NON_LTD" (
    P_BATCH_ID_R IN NUMBER
) AS

    V_SYS_DATE              VARCHAR2(15) := TO_CHAR(SYSDATE, 'YYYYMMDDHHMISS');
    N_MAX_SERIAL_NUM_R      NUMBER;
    V_SQLCODE               VARCHAR2(100);
    V_SQLERRM               VARCHAR2(500);
    LN_BATCH_ID_R           NUMBER := P_BATCH_ID_R;
    D_CURR_FISCAL_DATE      DATE;
BEGIN
	/* CURRENT FISCAL DATE */
	SELECT 
        DTR.D_CALENDAR_DATE_R 
    INTO
        D_CURR_FISCAL_DATE
    FROM
    (
        SELECT 
            N_MONTH_R,
            N_YEAR_R 
        FROM
            DIM_TIME_R 
        WHERE 
            D_CALENDAR_DATE_R = TO_DATE(SUBSTR(P_BATCH_ID_R, 1, 8), 'YYYYMMDD')
    ) DTR_CURR
    JOIN DIM_TIME_R DTR
    ON
    DTR.V_END_OF_FISCAL_MONTH_IND_R = 'Y'
    AND DTR.N_MONTH_R = DTR_CURR.N_MONTH_R
    AND DTR.N_YEAR_R = DTR_CURR.N_YEAR_R;

EXECUTE IMMEDIATE 'DELETE FROM STG_GRP_REINSURER_PREM_PCT_R WHERE V_LINE_OF_BUSINESS_R NOT IN (''LTD'',''VPL'',''LTD-SMALL'')';
INSERT INTO STG_GRP_REINSURER_PREM_PCT_R(
		N_POLICY_SK_R, 
		V_POLICY_NUMBER_R, 
		V_PRIMARY_REINSURER_R, 
		V_SECONDARY_REINSURER_R, 
		V_TERNARY_REINSURER_R, 
		N_PRIMARY_REINS_PREM_PCT_R, 
		N_SEC_REINS_PREM_PCT_R, 
		N_TERNARY_REINS_PREM_PCT_R, 
		N_TOTAL_REINS_PREM_PCT_R, 
		V_SIC_CODE_R, 
		V_MAX_MAX_BENEFIT_START_R, 
		V_MAX_MAX_BENEFIT_END_R, 
		V_PRODUCT_LINE_R, 
		V_PRODUCT_SUB_LINE_R, 
		V_MATRIX_IND_R, 
		V_LINE_OF_BUSINESS_R, 
		V_SIC_MAPPING_R, 
		V_OVERRIDE_DESCRIPTION_R, 
		FIC_MIS_DATE_R, 
		N_BATCH_ID_R, 
		N_SEQUENCE_NUMBER_R, 
		T_CREATION_DATE_R, 
		T_LAST_MODIFIED_DATE_R, 
		V_CREATED_BY_R, 
		V_LAST_MODIFIED_BY_R,
		SRRPRODUCTSUBLINE,
		SRRPRODUCTLINE,
		EXCLUSION_POLICY
	)
	SELECT
		N_POLICY_SK_R, 
		V_POLICY_NUMBER_R, 
		V_PRIMARY_REINSURER_R, 
		V_SECONDARY_REINSURER_R, 
		V_TERNARY_REINSURER_R, 
		N_PRIMARY_REINS_PREM_PCT_R, 
		N_SEC_REINS_PREM_PCT_R, 
		N_TERNARY_REINS_PREM_PCT_R, 
		N_TOTAL_REINS_PREM_PCT_R, 
		V_SIC_CODE_R, 
		V_MAX_MAX_BENEFIT_START_R, 
		V_MAX_MAX_BENEFIT_END_R, 
		V_PRODUCT_LINE_R, 
		V_PRODUCT_SUB_LINE_R, 
		V_MATRIX_IND_R, 
		V_LINE_OF_BUSINESS_R, 
		V_SIC_MAPPING_R, 
		V_OVERRIDE_DESCRIPTION_R, 
		FIC_MIS_DATE_R, 
		N_BATCH_ID_R, 
		N_SEQUENCE_NUMBER_R, 
		T_CREATION_DATE_R, 
		T_LAST_MODIFIED_DATE_R, 
		V_CREATED_BY_R, 
		V_LAST_MODIFIED_BY_R,
		SRRPRODUCTSUBLINE,
		SRRPRODUCTLINE,
		EXCLUSION_POLICY
	FROM (
WITH REINS_PREMIUM
AS (
	SELECT TEP.N_POLICY_SK_R
		,TO_CHAR(TEP.V_POLICY_NUMBER_R) AS TEP_POLICY_NUM
		,SRRR.V_REINSURER_NAME_R
		,DENSE_RANK() OVER (
			PARTITION BY SRRR.V_PRODUCT_LINE_R
			,SRRR.V_PRODUCT_SUB_LINE_R ORDER BY --SRRR.N_REINS_LOSS_MAX_R ASC
				SRRR.N_REINSURANCE_PREMIUM_RATE_R DESC
				,SRRR.N_REINS_LOSS_ATTACH_POINT_R ASC
			) AS REINS_RANK
		,
		--SPER.V_POLICY_NUMBER_R    AS SPER_POLICY_NUM,
		SRRR.N_REINS_LOSS_MAX_R
		,SRRR.N_REINS_LOSS_ATTACH_POINT_R
		,COALESCE(REGEXP_REPLACE(TEP.V_POLICY_NUMBER_R, '[^A-ZA-Z]', ''), SRRR.V_PRODUCT_LINE_R) AS V_PRODUCT_LINE_R
		,COALESCE(REGEXP_REPLACE(TEP.V_POLICY_NUMBER_R, '[^0-9]', ''), SRRR.V_PRODUCT_SUB_LINE_R) AS V_PRODUCT_SUB_LINE_R
		,SRRR.V_MATRIX_IND_R
		,SRMRMR.V_MAX_MAX_BENEFIT_START_R AS V_MAX_MAX_BENEFIT_START_R
		,
		/* Below is done so that we don't get values like 9999999 (Nov 2024) */
		CASE 
			WHEN SRMRMR.V_MAX_MAX_BENEFIT_END_R > 25000
				THEN MAX(FPDSR.V_OVERRIDE_DESCRIPTION_R)
			ELSE SRMRMR.V_MAX_MAX_BENEFIT_END_R
			END AS V_MAX_MAX_BENEFIT_END_R
		,NVL(DGPTYR.V_SIC_CODES_R, FGPR.V_SIC_CODE_R) AS V_SIC_CODE_R
		,SRMSMR.V_SIC_MAPPING_R
		,SPER.V_POLICY_NUMBER_R AS EXCLUSION_POLICY
		,SRRR.N_REINSURANCE_PREMIUM_RATE_R AS REINSURANCE_RATE_PCT
		,SRMRMR.N_REINSURANCE_PREMIUM_RATE_R
		,MAX(FPDSR.V_OVERRIDE_DESCRIPTION_R) AS V_OVERRIDE_DESCRIPTION_R
		,FGPR.V_LINE_OF_BUSINESS_R
		,SRRR.V_PRODUCT_SUB_LINE_R AS SRRPRODUCTSUBLINE
		,SRRR.V_PRODUCT_LINE_R AS SRRPRODUCTLINE
	FROM (
		SELECT /*+PARALLEL(8)*/
			N_POLICY_SK_R
			,V_POLICY_NUMBER_R
			,V_COVERAGE_CODE_R
		--D_CYCLE_DATE_R,
		--N_BATCH_ID_R
		FROM FCT_RPT_EARN_PREMIUM_SUMMARY_R
		WHERE D_CYCLE_DATE_R = D_CURR_FISCAL_DATE
		GROUP BY N_POLICY_SK_R
			,V_POLICY_NUMBER_R
			,V_COVERAGE_CODE_R
			--D_CYCLE_DATE_R,
			--N_BATCH_ID_R
		) TEP
	LEFT JOIN (
		SELECT
			/*+PARALLEL(8)*/ *
		FROM DIM_GRP_POLICY_DIR_R
		WHERE V_ACTIVE_STATUS_R = 'Y'
			AND N_POLICY_SK_R <> - 1
		) DGPDR ON DGPDR.N_POLICY_SK_R = TEP.N_POLICY_SK_R
		AND TEP.V_POLICY_NUMBER_R = DGPDR.V_POLICY_NUMBER_R
	JOIN FCT_GRP_POLICY_R FGPR ON DGPDR.N_POLICY_SK_R = FGPR.N_POLICY_SK_R
		AND FGPR.N_SOURCE_SYSTEM_KEY_R = DGPDR.N_SOURCE_SYSTEM_KEY_R
		AND DGPDR.N_POLICY_VERSION_NUMBER_R = FGPR.N_VERSION_NUMBER_R
	/* To get the correct SIC (Nov 2024), in case it's missing in FCT_GRP_POLICY_R */
	LEFT JOIN (
		SELECT V_SIC_CODES_R
			,N_PARTY_SK_R
		FROM DIM_GRP_PARTY_R
		WHERE V_ACTIVE_STATUS_R = 'Y'
		) DGPTYR ON DGPTYR.N_PARTY_SK_R = FGPR.N_CUST_PARTY_SK_R
	LEFT JOIN DIM_GRP_PRODUCT_R DGPR ON DGPR.V_COVERAGE_CODE_R = TEP.V_COVERAGE_CODE_R
	LEFT JOIN STG_PREMIUM_POLICY_EXCLUSIONS_R SPER ON TEP.V_POLICY_NUMBER_R = SPER.V_POLICY_NUMBER_R
		AND TRUNC(SPER.D_EXCLUSION_START_DATE_R) <= TO_DATE(SUBSTR(  P_BATCH_ID_R, 1, 8), 'YYYYMMDD')
		AND TRUNC(SPER.D_EXCLUSION_END_DATE_R) > TO_DATE(SUBSTR(P_BATCH_ID_R, 1, 8), 'YYYYMMDD')
	LEFT JOIN (
		SELECT
			/*+PARALLEL(8)*/ *
		FROM DIM_REINSURANCE_RATE_R DRR
		) SRRR ON TRUNC(SRRR.D_TREATY_YEAR_START_DATE_R) <= TO_DATE(SUBSTR(P_BATCH_ID_R, 1, 8), 'YYYYMMDD')
		AND TRUNC(SRRR.D_TREATY_YEAR_END_DATE_R) >= TO_DATE(SUBSTR(P_BATCH_ID_R, 1, 8), 'YYYYMMDD')
		AND (
			SRRR.V_PRODUCT_SUB_LINE_R = CASE 
				WHEN SPER.V_POLICY_NUMBER_R IS NOT NULL
					THEN CONCAT (
							REGEXP_REPLACE(SPER.V_POLICY_NUMBER_R, '[^0-9]', '')
							,CONCAT (
								'-'
								,DGPR.V_PRODUCT_SUB_LINE_CODE_R
								)
							)
				ELSE DGPR.V_PRODUCT_SUB_LINE_CODE_R
				END
			)
		AND (SRRR.V_PRODUCT_LINE_R = DGPR.V_PRODUCT_LINE_R)
	LEFT JOIN (
		SELECT *
		FROM DIM_PLAN_DESIGN_DIRECTORY_R
		WHERE V_ACTIVE_STATUS_R = 'Y'
			AND UPPER(NVL(V_COVERAGE_CODE_R, '@')) IN (
				'BENE1AMOUNT'
				,'MAXBENPCT'
				,'MAXBENINC'
				)
		) DPDDR ON DPDDR.N_POLICY_SK_R = FGPR.N_POLICY_SK_R
		AND DPDDR.N_PLAN_DESIGN_SRC_SYSTEM_KEY_R = DGPDR.N_SOURCE_SYSTEM_KEY_R
		AND DPDDR.N_PLAN_DESIGN_SRC_VERSION_NO_R = FGPR.N_VERSION_NUMBER_R
	LEFT JOIN (
		SELECT N_PLAN_DESIGN_SK_R
			,V_OVERRIDE_DESCRIPTION_R
		--RANK() OVER (PARTITION BY DPDDR.N_POLICY_SK_R ORDER BY V_OVERRIDE_DESCRIPTION_R DESC) AS DESC_RANK
		FROM FCT_PLAN_DESIGN_SUMMARY_R
		WHERE UPPER(NVL(V_COVERAGE_CODE_R, '@')) IN (
				'BENE1AMOUNT'
				,'MAXBENPCT'
				,'MAXBENINC'
				)
		) FPDSR ON FPDSR.N_PLAN_DESIGN_SK_R = DPDDR.N_PLAN_DESIGN_SK_R
	LEFT JOIN STG_REINS_MATRIX_SIC_MAPPING_R SRMSMR 
	ON 
	/*TRIM(SRMSMR.V_MATRIX_IND_R) = TRIM(CONCAT (
				CONCAT (
					DGPDR.V_POLICY_PREFIX_R
					,'-'
					)
				,SRRR.V_MATRIX_IND_R
				))*/
				 TRIM(SRMSMR.V_MATRIX_IND_R) =case when NVL(FGPR.V_DISTRIBUTION_CHANNEL_R,'1')   = 'MGIS' THEN
				 TRIM(CONCAT(CONCAT('MGIS', '-'), SRRR.V_MATRIX_IND_R))
				else
				 TRIM(CONCAT(CONCAT(DGPDR.V_POLICY_PREFIX_R, '-'), SRRR.V_MATRIX_IND_R))
				end
		AND TO_NUMBER(TRIM(NVL(DGPTYR.V_SIC_CODES_R, FGPR.V_SIC_CODE_R))) >= TO_NUMBER(TRIM(SRMSMR.N_SIC_RANGE_START_R))
		AND TO_NUMBER(TRIM(NVL(DGPTYR.V_SIC_CODES_R, FGPR.V_SIC_CODE_R))) <= TO_NUMBER(TRIM(SRMSMR.N_SIC_RANGE_END_R))
	LEFT JOIN STG_REINS_MATRIX_RT_MAPPING_R SRMRMR ON
		/* Earlier, we were comparing strings which was not giving the right results. So cast them to number to match with the STG (Nov 2024) */
		TO_NUMBER(TRIM(FPDSR.V_OVERRIDE_DESCRIPTION_R)) >= TO_NUMBER(TRIM(SRMRMR.V_MAX_MAX_BENEFIT_START_R))
		AND TO_NUMBER(TRIM(FPDSR.V_OVERRIDE_DESCRIPTION_R)) <= TO_NUMBER(TRIM(SRMRMR.V_MAX_MAX_BENEFIT_END_R))
		/*AND TRIM(SRMRMR.V_MATRIX_IND_R) = TRIM(CONCAT (
				CONCAT (
					DGPDR.V_POLICY_PREFIX_R
					,'-'
					)
				,SRRR.V_MATRIX_IND_R
				))*/
				AND  TRIM(SRMRMR.V_MATRIX_IND_R)=case when NVL(FGPR.V_DISTRIBUTION_CHANNEL_R,'1')   = 'MGIS' THEN
				 TRIM(CONCAT(CONCAT('MGIS', '-'), SRRR.V_MATRIX_IND_R))
				else 
				TRIM(CONCAT(CONCAT(DGPDR.V_POLICY_PREFIX_R, '-'), SRRR.V_MATRIX_IND_R)) 
				end 
		AND TO_CHAR(SRMRMR.V_SIC_MAPPING_R) = TO_CHAR(SRMSMR.V_SIC_MAPPING_R)
	GROUP BY TEP.N_POLICY_SK_R
		,TEP.V_POLICY_NUMBER_R
		,SRRR.V_REINSURER_NAME_R
		,SRRR.N_REINS_LOSS_MAX_R
		,SRRR.N_REINS_LOSS_ATTACH_POINT_R
		,SRRR.V_PRODUCT_LINE_R
		,SRRR.V_PRODUCT_SUB_LINE_R
		,SRRR.V_MATRIX_IND_R
		,V_OVERRIDE_DESCRIPTION_R
		,FGPR.V_LINE_OF_BUSINESS_R
		,NVL(DGPTYR.V_SIC_CODES_R, FGPR.V_SIC_CODE_R)
		,SRMSMR.V_SIC_MAPPING_R
		,SPER.V_POLICY_NUMBER_R
		,SRRR.N_REINSURANCE_PREMIUM_RATE_R
		,SRMRMR.N_REINSURANCE_PREMIUM_RATE_R
		,SRMRMR.V_MAX_MAX_BENEFIT_START_R
		,SRMRMR.V_MAX_MAX_BENEFIT_END_R
	)
SELECT N_POLICY_SK_R
	,V_POLICY_NUMBER_R
	,V_PRIMARY_REINSURER_R
	,V_SECONDARY_REINSURER_R
	,V_TERNARY_REINSURER_R
	,N_PRIMARY_REINS_PREM_PCT_R
	,N_SEC_REINS_PREM_PCT_R
	,N_TERNARY_REINS_PREM_PCT_R
	,N_TOTAL_REINS_PREM_PCT_R
	,V_SIC_CODE_R
	,V_MAX_MAX_BENEFIT_START_R
	,V_MAX_MAX_BENEFIT_END_R
	,V_PRODUCT_LINE_R
	,V_PRODUCT_SUB_LINE_R
	,V_MATRIX_IND_R
	,V_LINE_OF_BUSINESS_R
	,V_SIC_MAPPING_R
	,V_OVERRIDE_DESCRIPTION_R
	,TO_DATE(SUBSTR(P_BATCH_ID_R, 1, 8), 'YYYYMMDD') AS FIC_MIS_DATE_R
	,P_BATCH_ID_R AS N_BATCH_ID_R
	,ROWNUM AS N_SEQUENCE_NUMBER_R
	,SYSTIMESTAMP AS T_CREATION_DATE_R
	,SYSTIMESTAMP AS T_LAST_MODIFIED_DATE_R
	,'EDW' AS V_CREATED_BY_R
	,'EDW' AS V_LAST_MODIFIED_BY_R
	,SRRPRODUCTSUBLINE
	,SRRPRODUCTLINE
	,EXCLUSION_POLICY
FROM (
	SELECT N_POLICY_SK_R
		,TEP_POLICY_NUM AS V_POLICY_NUMBER_R
		,MAX(CASE 
				WHEN REINS_RANK = 1
					THEN V_REINSURER_NAME_R
				END) AS V_PRIMARY_REINSURER_R
		,MAX(CASE 
				WHEN REINS_RANK = 2
					THEN V_REINSURER_NAME_R
				END) AS V_SECONDARY_REINSURER_R
		,MAX(CASE 
				WHEN REINS_RANK = 3
					THEN V_REINSURER_NAME_R
				END) AS V_TERNARY_REINSURER_R
		,CASE 
			WHEN EXCLUSION_POLICY IS NOT NULL OR SRRPRODUCTSUBLINE IS NOT NULL
				THEN MAX(CASE 
							WHEN REINS_RANK = 1
								THEN REINSURANCE_RATE_PCT
							END)
			ELSE MAX(CASE 
						WHEN REINS_RANK = 1
							THEN N_REINSURANCE_PREMIUM_RATE_R
						END)
			END AS N_PRIMARY_REINS_PREM_PCT_R
		,CASE 
			WHEN EXCLUSION_POLICY IS NOT NULL OR SRRPRODUCTSUBLINE IS NOT NULL
				THEN MAX(CASE 
							WHEN REINS_RANK = 2
								THEN REINSURANCE_RATE_PCT
							END)
			ELSE MAX(CASE 
						WHEN REINS_RANK = 2
							THEN N_REINSURANCE_PREMIUM_RATE_R
						END)
			END AS N_SEC_REINS_PREM_PCT_R
		,CASE 
			WHEN EXCLUSION_POLICY IS NOT NULL OR SRRPRODUCTSUBLINE IS NOT NULL
				THEN MAX(CASE 
							WHEN REINS_RANK = 3
								THEN REINSURANCE_RATE_PCT
							END)
			ELSE MAX(CASE 
						WHEN REINS_RANK = 3
							THEN N_REINSURANCE_PREMIUM_RATE_R
						END)
			END AS N_TERNARY_REINS_PREM_PCT_R
		,CASE 
			WHEN EXCLUSION_POLICY IS NOT NULL OR SRRPRODUCTSUBLINE IS NOT NULL
				THEN SUM(CASE 
							WHEN REINS_RANK IN (
									1
									,2
									,3
									)
								THEN REINSURANCE_RATE_PCT
							END)
			ELSE SUM(CASE 
						WHEN REINS_RANK IN (
								1
								,2
								,3
								)
							THEN N_REINSURANCE_PREMIUM_RATE_R
						END)
			END AS N_TOTAL_REINS_PREM_PCT_R
		,V_SIC_CODE_R
		,V_MAX_MAX_BENEFIT_START_R
		,V_MAX_MAX_BENEFIT_END_R
		,V_PRODUCT_LINE_R
		,V_PRODUCT_SUB_LINE_R
		,V_MATRIX_IND_R
		,V_LINE_OF_BUSINESS_R
		,V_SIC_MAPPING_R
		,V_OVERRIDE_DESCRIPTION_R
		,SRRPRODUCTSUBLINE
		,SRRPRODUCTLINE
		,EXCLUSION_POLICY
		,RANK() OVER (
			PARTITION BY TEP_POLICY_NUM ORDER BY CAST(V_OVERRIDE_DESCRIPTION_R AS INTEGER) DESC NULLS LAST
			) AS OVER_RANK
	FROM REINS_PREMIUM
	GROUP BY N_POLICY_SK_R
		,TEP_POLICY_NUM
		,V_SIC_CODE_R
		,V_MAX_MAX_BENEFIT_START_R
		,V_MAX_MAX_BENEFIT_END_R
		,V_PRODUCT_SUB_LINE_R
		,V_PRODUCT_LINE_R
		,V_MATRIX_IND_R
		,V_LINE_OF_BUSINESS_R
		,V_SIC_MAPPING_R
		,V_OVERRIDE_DESCRIPTION_R
		,EXCLUSION_POLICY
		,SRRPRODUCTSUBLINE
		,SRRPRODUCTLINE
	)
WHERE OVER_RANK = 1
)
where V_LINE_OF_BUSINESS_R NOT IN ('LTD','VPL','LTD-SMALL');
	COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        V_SQLERRM := SUBSTR(SQLERRM, 1, 4000);
        RAISE_APPLICATION_ERROR(-20111, 'RAISE APPLICATION ERROR IN PRC_GRP_LOAD_STG_REINSURER_PREM_PCT_R_NON_LTD :->' || V_SQLERRM);
		END;

/

  GRANT EXECUTE ON "ATOMIC"."PRC_GRP_LOAD_STG_REINSURER_PREM_PCT_R_NON_LTD" TO "ATOMIC_ALL_RO";
