--------------------------------------------------------
--  DDL for Procedure PRC_GRP_LOAD_FCT_BILLING_POLICY_SUSPENSE_R_POSTED
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ATOMIC"."PRC_GRP_LOAD_FCT_BILLING_POLICY_SUSPENSE_R_POSTED" 
AS
  LC_SQLCODE VARCHAR2(300);
  LC_DAY     VARCHAR2(300);
  LC_SQLERRM VARCHAR2(4000);
  ln_N_BATCH_ID_R NUMBER :=TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD'));
BEGIN
  INSERT /*+APPEND*/
  INTO fct_billing_policy_suspense_r_posted
  SELECT *
  FROM fct_billing_policy_suspense_r ps
  WHERE ps.d_delete_date_r IS NOT NULL
  AND NOT EXISTS
    (SELECT 1
      /*b.N_SRC_SUSPENSE_PREMIUM_ID_R */
    FROM fct_billing_policy_suspense_r_posted b
    WHERE b.N_SRC_SUSPENSE_PREMIUM_ID_R = ps.N_SRC_SUSPENSE_PREMIUM_ID_R
    )
  AND ps.n_amount_r        <> 0
  AND ps.N_SRC_POLICY_ID_R <> 0 ;
  COMMIT;
EXCEPTION
WHEN OTHERS THEN
  LC_SQLCODE:=SQLCODE;
  LC_SQLERRM:=SUBSTR(SQLERRM,1,4000);
  INSERT
  INTO ATOMIC.PRCS_GRP_TBL_LOAD_DEBUG_TRC
    (
      V_JOB_NAME_R ,
      V_PKG_PRC_NAME_R ,
      N_SK_R ,
      V_NUMBER_R ,
      V_TRC_MSG_R ,
      N_BATCH_ID_R ,
      v_created_by_r ,
      V_LAST_MODIFIED_BY_R
    )
    VALUES
    (
      'GRP_LOAD_FCT_BILLING_POLICY_SUSPENSE_R_POSTED' ,
      'PRC_GRP_LOAD_FCT_BILLING_POLICY_SUSPENSE_R_POSTED' ,
      NULL ,
      NULL ,
      'Error in PRC_GRP_LOAD_FCT_BILLING_POLICY_SUSPENSE_R_POSTED :->'
      ||LC_SQLCODE
      ||'->'
      ||LC_SQLERRM ,
      ln_N_BATCH_ID_R ,
      'PRC_GRP_LOAD_FCT_BILLING_POLICY_SUSPENSE_R_POSTED' ,
      'PRC_GRP_LOAD_FCT_BILLING_POLICY_SUSPENSE_R_POSTED'
    );
  COMMIT;
  raise_application_error(-20001,'Error in PRC_GRP_LOAD_FCT_BILLING_POLICY_SUSPENSE_R_POSTED:->'||SQLERRM);
END;

/

  GRANT EXECUTE ON "ATOMIC"."PRC_GRP_LOAD_FCT_BILLING_POLICY_SUSPENSE_R_POSTED" TO "ODI_WORK_SCHEMA";
  GRANT EXECUTE ON "ATOMIC"."PRC_GRP_LOAD_FCT_BILLING_POLICY_SUSPENSE_R_POSTED" TO "ATOMIC_ALL_RW";
  GRANT EXECUTE ON "ATOMIC"."PRC_GRP_LOAD_FCT_BILLING_POLICY_SUSPENSE_R_POSTED" TO "ATOMIC_ALL_RO";
  GRANT EXECUTE ON "ATOMIC"."PRC_GRP_LOAD_FCT_BILLING_POLICY_SUSPENSE_R_POSTED" TO "EXT_DIGITAL_RO";
  GRANT EXECUTE ON "ATOMIC"."PRC_GRP_LOAD_FCT_BILLING_POLICY_SUSPENSE_R_POSTED" TO "EXT_EIS_RO";
  GRANT DEBUG ON "ATOMIC"."PRC_GRP_LOAD_FCT_BILLING_POLICY_SUSPENSE_R_POSTED" TO "ATOMIC_DEBUG";
