"PROCEDURE PRC_GRP_LOAD_FCT_LG_RESERVE_DETAILS_R_INCR_PREMIUM (
    P_BATCH_ID_R IN NUMBER
) AS
    V_SYS_DATE          	VARCHAR2(15) := TO_CHAR(SYSDATE, &apos;YYYYMMDDHHMISS&apos;);
    N_MAX_SERIAL_NUM_R  	NUMBER;
    V_SQLCODE           	VARCHAR2(100);
    V_SQLERRM           	VARCHAR2(500);
    LD_MIS_DATE_R       	DATE;
	LD_MIS_DATE_PREV_R  	DATE;
    LN_REP_MON_R        	VARCHAR2(8);
    LC_BKP_TBL_STR      	VARCHAR2(10) := TO_CHAR(SYSDATE, &apos;MMDDSS&apos;);
    LC_SQLCODE          	VARCHAR2(300);
    LC_SQLERRM          	VARCHAR2(4000);
    LD_SYSDATE          	DATE ;
    LC_TRCMSG           	VARCHAR2(4000) := &apos;TRACE MESSAGE:-&gt;&apos;;
    LN_START_TIME       	NUMBER;
    LN_N_BATCH_ID_R     	NUMBER := TO_NUMBER(TO_CHAR(SYSDATE, &apos;YYYYMMDD&apos;) || &apos;0000&apos;);
    LT_SYSTIMESTAMP     	TIMESTAMP := SYSDATE;
    LN_BATCH_ID_R       	NUMBER := P_BATCH_ID_R;
    LD_MIS_DATE_IBNR_R  	DATE;
	LD_MIS_DATE_OG_PREV_R   DATE;
    LC_DAY             	    VARCHAR2(30);
    ld_fic_mis_date 		DATE;



BEGIN

   SELECT TRUNC(D_START_DATE_R)+1 INTO ld_sysdate 
   FROM ATOMIC.PRCS_GRP_MONTH_END_CONFIG_R
   WHERE V_TABLE_NAME_R = &apos;RPT_BATCH_ID&apos;;

LC_TRCMSG:=LC_TRCMSG||CHR(13)||&apos;GET DAY&apos;;
SELECT TO_CHAR(SYSDATE,&apos;DAY&apos;)  INTO LC_DAY
FROM DUAL;
LC_TRCMSG:=LC_TRCMSG||CHR(13)||&apos;DAY IS:-&gt;&apos;||LC_DAY;



LC_TRCMSG:=LC_TRCMSG||CHR(13)||&apos;GET FISCAL MONTH END DATE +1 &apos;;
     SELECT D_CALENDAR_DATE_R +1 INTO LD_FIC_MIS_DATE
     FROM DIM_TIME_R D
     WHERE  V_END_OF_FISCAL_MONTH_IND_R = &apos;Y&apos;
	 AND TO_CHAR(D_CALENDAR_DATE_R,&apos;YYYYMM&apos;)=TO_CHAR(ld_sysdate,&apos;YYYYMM&apos;);
LC_TRCMSG:=LC_TRCMSG||CHR(13)||&apos;FISCAL MONTH END DATE +1 IS :-&gt;&apos;||LD_FIC_MIS_DATE;



LC_TRCMSG:= LC_TRCMSG||&apos;GETTING CURRENT CYCLE DATE from DIM_TIME_R &apos;||CHR(13);
   SELECT D_CALENDAR_DATE_R    INTO LD_MIS_DATE_R
    FROM DIM_TIME_R
    WHERE
		--N_MONTH_R=9 AND N_YEAR_R=2024 AND
        V_END_OF_FISCAL_MONTH_IND_R=&apos;Y&apos; 
        AND EXTRACT(MONTH FROM D_CALENDAR_DATE_R) = EXTRACT(MONTH FROM ld_sysdate)
        AND EXTRACT(YEAR FROM D_CALENDAR_DATE_R) = EXTRACT(YEAR FROM ld_sysdate); ---FOR ACTUAL RUN*/
LC_TRCMSG:= LC_TRCMSG||&apos;CURRENT CYCLE DATE LD_MIS_DATE_R --&gt;&apos;||LD_MIS_DATE_R ||CHR(13);	



LC_TRCMSG:= LC_TRCMSG||&apos;GETTING YEARMONTH FROM CURRENT CYCLE DATE &apos;||CHR(13);
  	SELECT TO_CHAR(D_CALENDAR_DATE_R, &apos;YYYYMM&apos;)  INTO LN_REP_MON_R
	FROM DIM_TIME_R
	WHERE
    -- N_MONTH_R=9 AND N_YEAR_R=2024 AND
	V_END_OF_FISCAL_MONTH_IND_R=&apos;Y&apos;
	AND	EXTRACT(MONTH FROM D_CALENDAR_DATE_R) = EXTRACT(MONTH FROM ld_sysdate)
	AND EXTRACT(YEAR FROM D_CALENDAR_DATE_R) = EXTRACT(YEAR FROM ld_sysdate);---FOR ACTUAL RUN*/
LC_TRCMSG:= LC_TRCMSG||&apos;YEARMONTH LN_REP_MON_R--&gt;  &apos;|| LN_REP_MON_R ||CHR(13); 



LC_TRCMSG:= LC_TRCMSG||&apos;GETTING THE PREVIOUS CYCLE DATE FROM DIM_TIME_R   &apos;||CHR(13);
	SELECT /*+PARALLEL(4)*/ D_CALENDAR_DATE_R INTO LD_MIS_DATE_PREV_R FROM
		( SELECT D_CALENDAR_DATE_R,RANK() OVER ( ORDER BY D_CALENDAR_DATE_R DESC) DATE_RANK
		  FROM		ATOMIC.DIM_TIME_R
		  WHERE		V_END_OF_FISCAL_MONTH_IND_R = &apos;Y&apos; AND D_CALENDAR_DATE_R &lt; LD_MIS_DATE_R
		) WHERE DATE_RANK =1;
LC_TRCMSG:= LC_TRCMSG||&apos;PREVIOUS CYCLE DATE FROM DIM_TIME_R --&gt; &apos;|| LD_MIS_DATE_PREV_R || CHR(13);


LC_TRCMSG:= LC_TRCMSG||&apos;Deleted the data from FCT_LG_RESERVE_DETAILS_R for IBNR&apos;||CHR(13);

DELETE FROM FCT_LG_RESERVE_DETAILS_R WHERE V_RESERVE_TYPE_IND_R=&apos;P&apos; AND D_RESERVE_VALUATION_DATE_R = LD_MIS_DATE_R;
COMMIT;

LC_TRCMSG:= LC_TRCMSG||&apos;Deleted the data from FCT_LG_RESERVE_DETAILS_R for IBNR&apos;||CHR(13);
LC_TRCMSG:= LC_TRCMSG||&apos;Inserting data into FCT_LG_RESERVE_DETAILS_R for IBNR for current cycle date &apos;||CHR(13);



INSERT   INTO ATOMIC.FCT_LG_RESERVE_DETAILS_R
		(
		V_RESERVE_TYPE_IND_R,
		N_RESERVE_DIRECT__GAAP__R,
		N_CHG_RESERVE_DIRECT__GAAP__R,
		N_RESERVE_DIRECT__STAT__R,
		N_CHG_RESERVE_DIRECT__STAT__R,
		N_ORIGINAL_RESERVE_R,
		N_CURRENT_RESERVE_R,
		N_GROSS_BENEFIT_R,
		N_NET_BENEFIT_R,
		N_CHECK_NET_BENEFIT_R,
		N_FINANCIAL_NET_BENEFIT_R,
		N_RESERVE_DIRECT_BEST_ESTMT_R,
		N_CHG_RSRV_DIRECT_BEST_ESTMT_R,
		N_BEST_ESTIMATE_NET_BENEFIT_R,
		V_PRICING_SSDI_ESTIMATED_IND_R,
		V_BEST_ESTMT_RESERVE_MODEL_R,
		N_RESERVE_DIRECT__FIELD__R,
		--N_RESERVE_CEDED__FIELD__R,
		-- N_RESERVE_NET__FIELD__R,
		N_CHG_RESERVE_DIRECT__FIELD__R,
		N_UNADJUSTD_RSRV_DIRECT_GAAP_R,
		N_UNADJUSTD_RSRV_DIRECT_STAT_R,
		D_RESERVE_VALUATION_DATE_R,
		V_COVERAGE_CODE_R,
		N_GAAP_IBNR_CEDED_R,
		N_STAT_IBNR_CEDED_R,
		V_POLICY_NUMBER_R,
		V_CLAIM_NUMBER_R,
		N_POLICY_SK_R,
		N_CLAIM_SK_R,
		FIC_MIS_DATE_R,
		N_BATCH_ID_R,
		N_SEQUENCE_NUMBER_R,
		T_CREATION_DATE_R,
		T_LAST_MODIFIED_DATE_R,
		V_CREATED_BY_R,
		V_LAST_MODIFIED_BY_R,
		V_CLAIM_IDENTIFIER_R,
		V_COV_GRP_ID_R
		)

SELECT 	V_RESERVE_TYPE_IND_R,
		N_RESERVE_DIRECT__GAAP__R,
		N_CHG_RESERVE_DIRECT__GAAP__R,
		N_RESERVE_DIRECT__STAT__R,
		N_CHG_RESERVE_DIRECT__STAT__R,
		N_ORIGINAL_RESERVE_R,
		N_CURRENT_RESERVE_R,
		N_GROSS_BENEFIT_R,
		N_NET_BENEFIT_R,
		N_CHECK_NET_BENEFIT_R,
		N_FINANCIAL_NET_BENEFIT_R,
		N_RESERVE_DIRECT_BEST_ESTMT_R,
		N_CHG_RSRV_DIRECT_BEST_ESTMT_R,
		N_BEST_ESTIMATE_NET_BENEFIT_R,
		V_PRICING_SSDI_ESTIMATED_IND_R,
		V_BEST_ESTMT_RESERVE_MODEL_R,
		N_RESERVE_DIRECT__FIELD__R,
		N_CHG_RESERVE_DIRECT__FIELD__R,
		N_UNADJUSTD_RSRV_DIRECT_GAAP_R,
		N_UNADJUSTD_RSRV_DIRECT_STAT_R,
		D_RESERVE_VALUATION_DATE_R,
		V_COVERAGE_CODE_R,
		N_GAAP_IBNR_CEDED_R,
		N_STAT_IBNR_CEDED_R,
		V_POLICY_NUMBER_R,
		V_CLAIM_NUMBER_R,
		N_POLICY_SK_R,
		-1 AS N_CLAIM_SK_R,
		SYSDATE AS FIC_MIS_DATE_R,
		LN_BATCH_ID_R,
		ROWNUM AS N_SEQUENCE_NUMBER_R,
		SYSDATE AS T_CREATION_DATE_R,
		SYSDATE AS T_LAST_MODIFIED_DATE_R,
		--LD_SYSDATE FIC_MIS_DATE_R,
		--TO_CHAR(LD_SYSDATE ,&apos;YYYYMMDD&apos;) N_BATCH_ID_R,
		--ROWNUM AS N_SEQUENCE_NUMBER_R,
		--LT_SYSTIMESTAMP AS T_CREATION_DATE_R,
		--LT_SYSTIMESTAMP AS T_LAST_MODIFIED_DATE_R,
		&apos;PRC_GRP_LOAD_FCT_LG_RESERVE_DETAILS_R_INCR_PREMIUM&apos; AS V_CREATED_BY_R,
		&apos;PRC_GRP_LOAD_FCT_LG_RESERVE_DETAILS_R_INCR_PREMIUM&apos; AS V_LAST_MODIFIED_BY_R,
		V_CLAIM_IDENTIFIER_R,
		V_COV_GRP_ID_R
		FROM (

		 SELECT 
		 LD_MIS_DATE_R AS D_RESERVE_VALUATION_DATE_R
		,&apos;P&apos; AS V_RESERVE_TYPE_IND_R
		,CAST (NULL AS INT)  AS N_RESERVE_DIRECT__GAAP__R
		,CAST (NULL AS INT)  AS N_CHG_RESERVE_DIRECT__GAAP__R
		,CAST (NULL AS INT)  AS N_RESERVE_DIRECT__STAT__R
		,CAST (NULL AS INT)  AS N_CHG_RESERVE_DIRECT__STAT__R
		,CAST (NULL AS INT) AS N_ORIGINAL_RESERVE_R
		,CAST (NULL AS INT)  AS N_CURRENT_RESERVE_R
		,CAST (NULL AS INT)  AS N_GROSS_BENEFIT_R
		,CAST (NULL AS INT)  AS N_NET_BENEFIT_R
		,CAST (NULL AS INT)  AS N_CHECK_NET_BENEFIT_R
		,CAST (NULL AS INT) AS N_FINANCIAL_NET_BENEFIT_R
		,SUM(CASE WHEN DIM_POL.V_POLICY_PREFIX_R IN ( &apos;GL&apos;, &apos;GGL&apos;, &apos;VG&apos;, &apos;SR&apos;, &apos;VAR&apos; ) THEN PREM.N_ANNUALIZED_PREMIUM_R * 0.15
									WHEN VW.NEW_POLICY_PREFIX IN (&apos;STD&apos;,&apos;TDB&apos;,&apos;TDI&apos;,&apos;DBL&apos; ,&apos;VPS&apos;, &apos;MAL&apos;, &apos;CTL&apos;) THEN  PREM.N_ANNUALIZED_PREMIUM_R  * 0.25
									WHEN DIM_POL.V_POLICY_PREFIX_R IN ( &apos;LTD&apos;, &apos;VLT&apos;,&apos;VPL&apos;  ) THEN ( ( NVL(POL_DTL.V_ELIM_PERIOD_R,0) + 60) / 365 ) * PREM.N_ANNUALIZED_PREMIUM_R* 0.80
									WHEN (DIM_POL.V_POLICY_PREFIX_R = &apos;VIP&apos; AND DIM_PRODUCT.V_BASIC_PRODUCT_LINE_CODE_R = &apos;STD&apos;) THEN PREM.N_ANNUALIZED_PREMIUM_R  * 0.25
									WHEN ( DIM_POL.V_POLICY_PREFIX_R = &apos;VIP&apos; AND DIM_PRODUCT.V_BASIC_PRODUCT_LINE_CODE_R  = &apos;LTD&apos;) THEN ( ( NVL(POL_DTL.V_ELIM_PERIOD_R,0) + 60) / 365 ) * PREM.N_ANNUALIZED_PREMIUM_R  * 0.80
									END ) 
									AS N_RESERVE_DIRECT_BEST_ESTMT_R
		,CAST (NULL AS INT)  AS N_CHG_RSRV_DIRECT_BEST_ESTMT_R
		,CAST (NULL AS INT)  AS N_BEST_ESTIMATE_NET_BENEFIT_R
		,CAST (NULL AS VARCHAR(100))  AS V_PRICING_SSDI_ESTIMATED_IND_R
		,CAST (NULL AS VARCHAR(100)) AS V_BEST_ESTMT_RESERVE_MODEL_R
		,SUM(CASE WHEN DIM_POL.V_POLICY_PREFIX_R IN ( &apos;GL&apos;, &apos;GGL&apos;, &apos;VG&apos;, &apos;SR&apos;, &apos;VAR&apos; ) THEN PREM.N_ANNUALIZED_PREMIUM_R * 0.15
									WHEN VW.NEW_POLICY_PREFIX IN (&apos;STD&apos;,&apos;TDB&apos;,&apos;TDI&apos;,&apos;DBL&apos; ,&apos;VPS&apos;, &apos;MAL&apos;, &apos;CTL&apos;) THEN  PREM.N_ANNUALIZED_PREMIUM_R  * 0.25
									WHEN DIM_POL.V_POLICY_PREFIX_R IN ( &apos;LTD&apos;, &apos;VLT&apos;,&apos;VPL&apos;  ) THEN ( ( NVL(POL_DTL.V_ELIM_PERIOD_R,0) + 60) / 365 ) * PREM.N_ANNUALIZED_PREMIUM_R* 0.80
									WHEN (DIM_POL.V_POLICY_PREFIX_R = &apos;VIP&apos; AND DIM_PRODUCT.V_BASIC_PRODUCT_LINE_CODE_R = &apos;STD&apos;) THEN PREM.N_ANNUALIZED_PREMIUM_R  * 0.25
									WHEN ( DIM_POL.V_POLICY_PREFIX_R = &apos;VIP&apos; AND DIM_PRODUCT.V_BASIC_PRODUCT_LINE_CODE_R  = &apos;LTD&apos;) THEN ( ( NVL(POL_DTL.V_ELIM_PERIOD_R,0) + 60) / 365 ) * PREM.N_ANNUALIZED_PREMIUM_R  * 0.80
									END ) 
									AS N_RESERVE_DIRECT__FIELD__R
		,CAST (NULL AS INT)  AS N_CHG_RESERVE_DIRECT__FIELD__R
		,CAST (NULL AS INT)  AS N_UNADJUSTD_RSRV_DIRECT_GAAP_R
		,CAST (NULL AS INT)  AS N_UNADJUSTD_RSRV_DIRECT_STAT_R
		,(CASE WHEN DIM_POL.V_POLICY_PREFIX_R = &apos;MAL&apos; THEN CONCAT(DIM_POL.V_POLICY_PREFIX_R,DIM_POL.V_POLICY_SUFFIX_R) ELSE DIM_POL.V_POLICY_NUMBER_R END) V_POLICY_NUMBER_R
		,&apos;UNKNOWN&apos; AS V_CLAIM_NUMBER_R
		,DIM_POL.N_POLICY_SK_R AS N_POLICY_SK_R
		,LD_MIS_DATE_R AS D_CYCLE_DATE_R
		,DIM_PRODUCT.V_COVERAGE_CODE_R AS V_COVERAGE_CODE_R
		,CAST (NULL AS INT) AS N_GAAP_IBNR_CEDED_R
		,CAST (NULL AS INT) AS N_STAT_IBNR_CEDED_R
		,CAST (NULL AS VARCHAR(100)) AS V_CLAIM_IDENTIFIER_R
		,CAST (NULL AS VARCHAR(100)) AS V_COV_GRP_ID_R
		FROM  ATOMIC.FCT_RPT_ANN_PREM_SUMMARY_R  PREM
			INNER JOIN (SELECT N_POLICY_SK_R,V_POLICY_NUMBER_R,V_POLICY_PREFIX_R,V_POLICY_SUFFIX_R FROM ATOMIC.DIM_GRP_POLICY_DIR_R  DIM
			WHERE DIM.V_ACTIVE_STATUS_R =&apos;Y&apos;) DIM_POL 
				ON  PREM.N_POLICY_SK_R = DIM_POL.N_POLICY_SK_R
			INNER JOIN 
			(SELECT REPLACE(VW.OLD_V_POLICY_PREFIX_R,&apos;G&apos;,VW.V_POLICY_PREFIX_R)  AS NEW_POLICY_PREFIX,VW.* FROM VW_DIM_GRP_POLICY_DIR_R_POLICY_PREFIX_BRIDGE_MV  VW)VW
				ON  VW.V_POLICY_PREFIX_R = DIM_POL.V_POLICY_PREFIX_R
				AND VW.V_POLICY_SUFFIX_R = DIM_POL.V_POLICY_SUFFIX_R			 
			INNER JOIN ATOMIC.DIM_TIME_R DIM_TIME 
				ON PREM.D_CYCLE_DATE_R = DIM_TIME.D_CALENDAR_DATE_R
			LEFT JOIN ATOMIC.DIM_GRP_PRODUCT_R  DIM_PRODUCT
				ON PREM.V_COVERAGE_CODE_R = DIM_PRODUCT.V_COVERAGE_CODE_R
			INNER JOIN (SELECT V_POLICY_PREFIX_R,V_POLICY_SUFFIX_R,V_ELIM_PERIOD_R,N_POLICY_SK_R FROM ATOMIC.RPT_POLICY_DTL_R 
						WHERE N_YEARMONTH_R = LN_REP_MON_R)POL_DTL
				ON DIM_POL.N_POLICY_SK_R = POL_DTL.N_POLICY_SK_R  

			WHERE  PREM.D_CYCLE_DATE_R=LD_MIS_DATE_R
			GROUP BY LD_MIS_DATE_R,(CASE WHEN DIM_POL.V_POLICY_PREFIX_R = &apos;MAL&apos; THEN CONCAT(DIM_POL.V_POLICY_PREFIX_R,DIM_POL.V_POLICY_SUFFIX_R) ELSE DIM_POL.V_POLICY_NUMBER_R END),
			DIM_PRODUCT.V_COVERAGE_CODE_R,&apos;P&apos; ,&apos;UNKNOWN&apos;,DIM_TIME.D_CALENDAR_DATE_R,DIM_POL.N_POLICY_SK_R
			)
            ;
            COMMIT;

LC_TRCMSG:= LC_TRCMSG||&apos;Data inserted to FCT_LG_RESERVE_DETAILS_R FOR P IND &apos;||CHR(13);



   INSERT INTO ATOMIC.PRCS_GRP_TBL_LOAD_DEBUG_TRC (
            V_JOB_NAME_R,
            V_PKG_PRC_NAME_R,
            N_SK_R,
            V_NUMBER_R,
            V_TRC_MSG_R,
            N_BATCH_ID_R,
            V_CREATED_BY_R,
            V_LAST_MODIFIED_BY_R
        ) VALUES (
            &apos;PRC_GRP_LOAD_FCT_LG_RESERVE_DETAILS_R_INCR_PREMIUM&apos;,
            &apos;PRC_GRP_LOAD_FCT_LG_RESERVE_DETAILS_R_INCR_PREMIUM&apos;,
            NULL,
            NULL,
            &apos;WHEN OTHERS RAISED IN PRC_GRP_LOAD_FCT_LG_RESERVE_DETAILS_R_INCR_PREMIUM :-&gt;&apos;
            || LC_TRCMSG
            || LC_SQLCODE
            || &apos;-&gt;&apos;
            || LC_SQLERRM,
            LN_N_BATCH_ID_R,
            &apos;PRC_GRP_LOAD_FCT_LG_RESERVE_DETAILS_R_INCR_PREMIUM&apos;,
            &apos;PRC_GRP_LOAD_FCT_LG_RESERVE_DETAILS_R_INCR_PREMIUM&apos;
        );

        COMMIT;			

END;"